version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - wmkdev
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: "@hapi/boom"
    versions:
    - 9.1.1
